export const ROLES = {
    ADMIN: 'admin',
    EDITOR: 'editor',
    VIEWER: 'viewer'
  };
  
  export const PERMISSIONS = {
    // Pages
    DASHBOARD: [ROLES.ADMIN, ROLES.EDITOR, ROLES.VIEWER],
    MESSAGES: [ROLES.ADMIN, ROLES.EDITOR],
    MESSAGES_DELETE: [ROLES.ADMIN],
    MESSAGES_READ: [ROLES.ADMIN, ROLES.EDITOR, ROLES.VIEWER],
    
    CALENDAR: [ROLES.ADMIN, ROLES.EDITOR],
    CALENDAR_EDIT: [ROLES.ADMIN, ROLES.EDITOR],
    CALENDAR_DELETE: [ROLES.ADMIN],
    
    USERS: [ROLES.ADMIN],
    USERS_EDIT: [ROLES.ADMIN],
    USERS_DELETE: [ROLES.ADMIN],
    
    ANNOUNCEMENTS: [ROLES.ADMIN, ROLES.EDITOR],
    ANNOUNCEMENTS_EDIT: [ROLES.ADMIN, ROLES.EDITOR],
    ANNOUNCEMENTS_DELETE: [ROLES.ADMIN]
  };