import { HeaderAdmin } from "@/components/HeaderAdmin";
import MessageList from "@/components/MessageList";
import Head from "next/head";
import CheckLogin from "@/components/CheckLogin";

export default function Messages() {
  return (
    <CheckLogin>
      <Head>
        <title>Message - Admin | Voice of God Tabernacle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderAdmin />
      <MessageList />
    </CheckLogin>
  );
}
