import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";

import { LanguageProvider } from "@/components/contexts/LanguageContext";
import Banner from "@/components/contacts/Banner";
import Form from "@/components/contacts/Form";
import UsefulLinks from "@/components/UsefulLinks";
import Information from "@/components/contacts/Information";
export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact | Voice of God Tabernacle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/VGR.png" />
      </Head>
      <Header />

      <main>
          <Banner />
          <Form />
          <Information />
          <UsefulLinks />
      </main>
      <Footer />
    </>
  );
}
