import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";

import { LanguageProvider, useLanguage } from "@/components/contexts/LanguageContext";
import UsefulLinks from "@/components/UsefulLinks";
import Banner from "@/components/history/Banner";
import Blockquote from "@/components/history/Blockquote";
import Story from "@/components/history/Story";
import Album from "@/components/history/Album";

export default function History() {

  const {language} = useLanguage();

  return (
    <>
      <Head>
        <title>{language === "fr" ? "Histoire | " : "History | "}Voice of God Tabernacle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Banner />
        <Blockquote />  
        <Story />
        <Album />
        <UsefulLinks />
        
      </main>
      <Footer />
    </>
  );
}
