import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";

import { LanguageProvider } from "@/components/contexts/LanguageContext";
export default function Home() {
  return (
    <LanguageProvider>
    <Head>
      <title>Voice of God Tabernacle</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <main></main>
    <Footer />
  </LanguageProvider>
  );
}
