import { HeaderAdmin } from "./components/HeaderAdmin";
import MessageList from "./components/MessageList";
import CheckLogin from "./services/CheckLogin";
import Head from "next/head";

export default function Messages() {
  return (
    <CheckLogin>
      <Head>
        <title>Services | Voice of God Tabernacle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderAdmin />
      <MessageList />
    </CheckLogin>
  );
}
